<?php

/**
 * Create an event a standalone installation can serve — without a Live! to
 * record one from.
 *
 *   php install/make-event.php my-event.json
 *   php install/make-event.php my-event.json --out=events/showcase --set-capture
 *
 * Everything a standalone installation shows comes from a **capture**: a flat
 * directory of JSON files in Live!'s payload shape, normally recorded off a
 * running instance by `tests/capture.mjs`. That is circular for the person this
 * mode exists for — you need a Live! to make the thing that lets you run
 * without a Live!. This is the other way in: a small description of an event,
 * and the capture comes out.
 *
 * WHAT IT DELIBERATELY DOES NOT DO: ROSTERS
 *
 * This writes **metadata only** — the event, the teams' names, and the games.
 * Every team it writes has an empty squad, and that is not an omission.
 *
 * The commentary desk already has a round trip for players: it exports a team's
 * sheet, the team fills it in, and the desk imports it back. Standalone, that
 * import also **creates** the players it does not recognise (`shared/roster.php`
 * — and only standalone, because hosted the squad belongs to UltiOrganizer and
 * an import must never invent people into somebody's tournament).
 *
 * So the division is: this tool writes what a person types once and never
 * touches again, and the roster arrives through the door it already has. There
 * is no second CSV format and nothing new to learn.
 *
 * WHY THIS CAN BE SMALL AT ALL
 *
 * Because **match control already keeps the score and the clock**
 * (`docs/MATCHCONTROL.md`), so nothing here has to. Every game it writes starts
 * 0–0 with no goals and no events, and a phone at the pitch supplies the rest.
 *
 * THREE RULES IT FOLLOWS, EACH OF WHICH IS A BUG IF IGNORED
 *
 * **Absent is not zero.** A new event has no tournament totals, no history, no
 * seeds, no standings, no spirit. Live! would send those as `0`; this omits
 * them. `docs/STANDALONE.md` §7 is emphatic about why: a player sheet showing
 * `0 G · 0 A` for somebody who has scored nine is a lie told on air, and every
 * consumer here already draws nothing for an absent field.
 *
 * **No `meta` block.** A recorded payload carries the server clock it was
 * generated by, and the scoreboard uses `meta.generated_timestamp` to work out
 * its own skew. A static file authored today and served next month has no such
 * clock, and a stale one would skew every overlay by the difference. Omitted,
 * the skew stays zero and the pollers fall back to their own intervals, which
 * is the correct answer rather than a convenient one.
 *
 * **Ids are yours, and they must not move.** `conf/score-<game>.json` is keyed
 * by game id, and so is every URL typed into a video switcher; a team's roster
 * and the desk's prepared notes are keyed by team and player id. Regenerating
 * an event with different ids therefore silently detaches a game's score and a
 * team's squad. So team and game ids are required rather than invented.
 */

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(404);

    exit;
}

$root = dirname(__DIR__);

/**
 * Options and arguments, in any order.
 *
 * Not `getopt()`: it stops at the first non-option argument, so
 * `make-event.php event.json --set-capture` parses the flag as nothing at all
 * and silently does the opposite of what was asked. Found by running it.
 */
$opts = [];
$args = [];
foreach (array_slice($argv, 1) as $arg) {
    if (!str_starts_with($arg, '--')) {
        $args[] = $arg;
        continue;
    }
    $body = substr($arg, 2);
    $eq = strpos($body, '=');
    if ($eq === false) {
        $opts[$body] = false;
    } else {
        $opts[substr($body, 0, $eq)] = substr($body, $eq + 1);
    }
}

$known = ['out', 'force', 'set-capture', 'help'];
foreach (array_keys($opts) as $name) {
    if (!in_array($name, $known, true)) {
        fwrite(STDERR, 'make-event: unknown option --' . $name . "\n");

        exit(1);
    }
}

if (isset($opts['help']) || count($args) !== 1) {
    fwrite(STDOUT, <<<TEXT
    Create a capture from a description of an event. Metadata only — the squads
    arrive through the commentary desk's own roster import.

      php install/make-event.php <event.json> [options]

      --out=DIR       where to write it, relative to this directory.
                      Default: events/<slug of the event name>
      --set-capture   point conf/local-config.php at it when done, so the
                      installation serves this event immediately.
      --force         replace an existing capture directory, and the stored
                      description in conf/event.json.

    The event file, in full:

      {
        "event": "Spring Showcase",
        "season": "SHOW2027",
        "place": "Riverside Fields",
        "teams": [
          { "id": 1, "name": "Mosquitos", "short": "MOS" },
          { "id": 2, "name": "Lemmings",  "short": "LEM" }
        ],
        "games": [
          { "id": 1, "home": 1, "visitor": 2, "field": "1",
            "time": "2027-05-01 10:00", "name": "Semi-final" }
        ]
      }

    Optional, with the defaults shown:

      "type": "open"            open | women | mixed | masters ...
      "organizer": ""
      "logo": null              a URL for the tournament logo on the stage
      "pool": { "name": "Pool A", "winningscore": 15, "halftime": 8,
                "timecap": null, "timeouts": 2, "timeoutsper": "half",
                "timeoutlen": 70 }
      per game: "status": "scheduled" | "ongoing" | "completed"

    Note halftime is a SCORE here (the point the break falls at), which is what
    a pool means by it.

    Afterwards, per team: open the commentary desk, export that team's sheet,
    have them fill in Number and Name, and import it back. That is what puts
    players on a roster.

    TEXT);

    exit(isset($opts['help']) ? 0 : 1);
}

/** Report and stop. */
function fail(string $message): never
{
    fwrite(STDERR, 'make-event: ' . $message . "\n");

    exit(1);
}

require_once __DIR__ . '/../shared/event.php';
require_once __DIR__ . '/../shared/mode.php';

use Overlays\Event;
use Overlays\Mode;

$sourcePath = $args[0];
if (!is_file($sourcePath)) {
    fail('no such file: ' . $sourcePath);
}
$raw = json_decode((string) file_get_contents($sourcePath), true);
if (!is_array($raw)) {
    fail($sourcePath . ' is not valid JSON: ' . json_last_error_msg());
}

/**
 * Everything wrong with the file, not the first thing wrong with it.
 *
 * Somebody hand-editing JSON wants the whole list; being told about one missing
 * field per run is six runs to fix six typos. `Overlays\Event::validate()`
 * collects them for the same reason the page does — it is the same validation.
 */
$checked = Event::validate($raw);
if ($checked['problems'] !== []) {
    fwrite(STDERR, 'make-event: ' . count($checked['problems']) . ' problem'
        . (count($checked['problems']) === 1 ? '' : 's') . ' in ' . $sourcePath . ":\n");
    foreach ($checked['problems'] as $p) {
        fwrite(STDERR, '  - ' . $p . "\n");
    }

    exit(1);
}
$spec = $checked['spec'];

$out = isset($opts['out']) ? trim((string) ($opts['out'] ?: '')) : '';
if ($out === '') {
    $out = 'events/' . Event::slug($spec);
}
// Inside this installation, and nowhere else. `--out` is a path from a shell,
// so it is somebody who already has one — but a slip like `--out=../../public`
// would write a directory of JSON over whatever is there, and refusing costs a
// line.
$out = trim(str_replace('\\', '/', $out), '/');
$outDir = $root . '/' . $out;
$resolved = realpath(dirname($outDir));
if ($out === '' || str_contains('/' . $out . '/', '/../')
    || $resolved === false || !str_starts_with($resolved . '/', realpath($root) . '/')) {
    fail('--out must name a directory inside this installation: ' . $out);
}

if (is_dir($outDir) && !isset($opts['force'])) {
    fail($out . ' already exists. Pass --force to replace it.');
}

// The stored description is overwritten too, and it may be one somebody
// authored in the editor rather than from this file. Guarded by the same flag
// as the capture, because losing it silently is the worse of the two.
if (is_file(Overlays\Event::STORE) && !isset($opts['force'])) {
    fail('conf/event.json already describes an event. Pass --force to replace it.');
}

$built = Event::build($spec, $outDir);
if (!$built['ok']) {
    fail((string) ($built['error'] ?? 'could not write the capture.'));
}

// Stored as well as built, so the page at ?view=event opens on this event
// rather than on an empty form — the two authoring surfaces are one event.
if (!Event::save($spec)) {
    fwrite(STDERR, "make-event: warning — the capture was written but "
        . "conf/event.json could not be, so the editor page will not see it.\n");
}

if (isset($opts['set-capture'])) {
    $configPath = $root . '/conf/local-config.php';
    if (!is_file($configPath)) {
        fail('conf/local-config.php does not exist yet — run install/make-config.php first.');
    }
    $config = require $configPath;
    if (!is_array($config)) {
        fail('conf/local-config.php did not return an array.');
    }
    $config['capture'] = $out;
    // Through Overlays\Mode, which is also what the editor page uses — this was
    // a second copy of the same twenty lines and it had already drifted: only
    // the page invalidated the compiled config, so the same edit took effect at
    // once there and appeared to do nothing here.
    if (!Mode::saveLocalConfig($config)) {
        fail('cannot write ' . $configPath);
    }
}

fwrite(STDOUT, 'Wrote ' . count($built['files']) . ' files to ' . $out . "\n"
    . '  event: ' . $spec['event'] . ' (' . $spec['season'] . ")\n"
    . '  teams: ' . implode(', ', array_map(
        static fn (array $t): string => $t['name'] . ' [' . $t['id'] . ']',
        $spec['teams']
    )) . "\n"
    . '  games: ' . implode(', ', array_keys($spec['games'])) . "\n"
    . (isset($opts['set-capture'])
        ? "  capture: set in conf/local-config.php\n"
        : "\nPoint the installation at it by setting 'capture' => '" . $out
            . "' in conf/local-config.php, or re-run with --set-capture.\n")
    . "\nThe same event is editable in a browser at ?view=event. Squads are empty:\n"
    . "add players at the commentary desk, by hand or from the team's own sheet.\n"
    . "The score and clock are match control's: /k/<game>.\n");
