<?php

/**
 * An event a standalone installation can serve, and the capture built from it.
 *
 * Two things live here and they are deliberately separate:
 *
 *   the DESCRIPTION  a small document a person authors — the event's name, the
 *                    teams' names, the games. `conf/event.json`.
 *   the CAPTURE      the flat directory of JSON files in Live!'s payload shape
 *                    that every page actually reads. `events/<slug>/`.
 *
 * The description is the source and the capture is derived, rebuilt from it on
 * every save. That is what lets the same authoring exist twice — as a CLI for a
 * person with shell (`install/make-event.php`) and as a page for a person with
 * a browser (`event.php`) — without two implementations of the payload shape,
 * which is the one thing in this project that must not have two of.
 *
 * WHY THE DESCRIPTION IS NOT ITSELF THE PAYLOAD
 *
 * Because the payload shape is Live!'s, warts included — `teams.hometeam`, a
 * pool's `halftime` meaning a SCORE, an error body that is a string — and
 * `docs/STANDALONE.md` §7 is emphatic that nothing above `shared/provider.js`
 * should learn a second one. Asking a person to author that directly would be
 * asking them to hand-write forty fields per game, most of which mean nothing
 * without a database behind them. So they author fifteen and this derives the
 * rest.
 *
 * WHAT IT DELIBERATELY DOES NOT HOLD
 *
 * **Squads** (`shared/roster.php`) and **the score and clock**
 * (`shared/score.php`). Both are written during the day by somebody else, from
 * a different surface, and folding them in here would mean an operator
 * correcting a team name could overwrite a roster or a score. The description
 * is the part nobody touches once the day starts.
 *
 * THREE RULES THE BUILD FOLLOWS, EACH OF WHICH IS A BUG IF IGNORED
 *
 * **Absent is not zero.** A new event has no totals, no history, no seeds, no
 * standings. Live! sends those as `0`; this omits them, because a player sheet
 * showing `0 G · 0 A` for somebody who has scored nine is a lie told on air and
 * every consumer here already draws nothing for an absent field.
 *
 * **No `meta` block.** A recorded payload carries the server clock it was
 * generated by, and the scoreboard derives its own skew from
 * `meta.generated_timestamp`. A static file authored today and served next
 * month has no such clock; a stale one would skew every overlay by the
 * difference. Omitted, the skew stays zero and the pollers fall back to their
 * own intervals.
 *
 * **Ids belong to the author and must not move.** `conf/score-<game>.json` is
 * keyed by game id, and so is every URL typed into a video switcher; a squad
 * and its prepared notes are keyed by team and player id. So ids are carried
 * through edits rather than reassigned, and `validate()` refuses a duplicate
 * rather than quietly renumbering.
 */

namespace Overlays;

final class Event
{
    /** Where the authored description lives. Denied over HTTP, like the rest of conf/. */
    public const STORE = __DIR__ . '/../conf/event.json';

    /** One series, one pool. A bracket is a schedule, and this is not one yet. */
    private const SERIES_ID = 100;
    private const POOL_ID = 200;

    /** @return array{spec: array, problems: list<string>} */
    public static function validate(array $raw): array
    {
        $problems = [];
        $bad = static function (string $m) use (&$problems): void { $problems[] = $m; };

        $str = static fn (array $a, string $k, string $d = ''): string
            => is_scalar($a[$k] ?? null) ? trim((string) $a[$k]) : $d;
        $num = static function (array $a, string $k, ?int $d) {
            if (!array_key_exists($k, $a) || $a[$k] === null || $a[$k] === '') {
                return $d;
            }

            return is_numeric($a[$k]) ? (int) $a[$k] : $d;
        };

        $spec = [];
        $spec['event'] = $str($raw, 'event');
        if ($spec['event'] === '') {
            $bad('The event needs a name — it is what the stage shows.');
        }

        // The season id ends up in URLs and filenames, so it is constrained
        // rather than free text.
        $season = strtoupper($str($raw, 'season'));
        if ($season === '') {
            $season = strtoupper(substr(
                preg_replace('/[^A-Za-z0-9]/', '', $spec['event']) ?: 'EVENT',
                0,
                8
            ));
        }
        if (preg_match('/^[A-Z0-9_-]{2,32}$/', $season) !== 1) {
            $bad('The season id must be 2-32 characters of A-Z, 0-9, _ or -.');
        }
        $spec['season'] = $season;

        $spec['place'] = $str($raw, 'place', 'Field');
        $spec['type'] = $str($raw, 'type', 'open');
        $spec['organizer'] = $str($raw, 'organizer');
        $spec['logo'] = $str($raw, 'logo');

        $poolRaw = is_array($raw['pool'] ?? null) ? $raw['pool'] : [];
        $spec['pool'] = [
            'name' => $str($poolRaw, 'name', 'Pool A'),
            'winningscore' => $num($poolRaw, 'winningscore', 15),
            // A pool's "halftime" is the SCORE the break falls at, not a
            // duration. Live! spells it the same way and it catches people out
            // every time, so the form says so too.
            'halftime' => $num($poolRaw, 'halftime', 8),
            'timecap' => $num($poolRaw, 'timecap', null),
            'scorecap' => $num($poolRaw, 'scorecap', null),
            'timeouts' => $num($poolRaw, 'timeouts', 2),
            'timeoutsper' => $str($poolRaw, 'timeoutsper', 'half'),
            'timeoutlen' => $num($poolRaw, 'timeoutlen', 70),
        ];
        if (!in_array($spec['pool']['timeoutsper'], ['half', 'game'], true)) {
            $bad('Timeouts are counted per "half" or per "game".');
        }

        $spec['teams'] = [];
        $teams = is_array($raw['teams'] ?? null) ? array_values($raw['teams']) : [];
        if (count($teams) < 2) {
            $bad('An event needs at least two teams.');
        }
        $nextTeam = 1;
        foreach ($teams as $i => $t) {
            if (!is_array($t)) {
                continue;
            }
            $name = $str($t, 'name');
            if ($name === '') {
                $bad('Team ' . ($i + 1) . ' has no name.');
                continue;
            }
            // An id already present is kept for ever: it keys this team's squad
            // and their prepared notes. Only a new row is assigned one.
            $id = $num($t, 'id', null);
            if ($id === null || $id < 1) {
                while (isset($spec['teams'][$nextTeam])) {
                    $nextTeam += 1;
                }
                $id = $nextTeam;
            }
            if (isset($spec['teams'][$id])) {
                $bad('Two teams share the id ' . $id . '.');
                continue;
            }
            $short = $str($t, 'short');
            if ($short === '') {
                // Used only where there genuinely is not room, and the overlays
                // fall back to the full name, so a rough guess beats nothing.
                $short = strtoupper(mb_substr(
                    preg_replace('/[^\p{L}\p{N} ]/u', '', $name) ?: $name,
                    0,
                    3
                ));
            }
            $spec['teams'][$id] = ['id' => $id, 'name' => $name, 'short' => $short];
        }

        $spec['games'] = [];
        $games = is_array($raw['games'] ?? null) ? array_values($raw['games']) : [];
        if ($games === []) {
            $bad('An event needs at least one game.');
        }
        $nextGame = 1;
        foreach ($games as $i => $g) {
            if (!is_array($g)) {
                continue;
            }
            $id = $num($g, 'id', null);
            if ($id === null || $id < 1) {
                while (isset($spec['games'][$nextGame])) {
                    $nextGame += 1;
                }
                $id = $nextGame;
            }
            if (isset($spec['games'][$id])) {
                $bad('Two games share the id ' . $id . '.');
                continue;
            }
            $home = $num($g, 'home', null);
            $visitor = $num($g, 'visitor', null);
            $label = 'Game ' . $id;
            if ($home === null || !isset($spec['teams'][$home])) {
                $bad($label . ': the home team is not one of the teams above.');
                continue;
            }
            if ($visitor === null || !isset($spec['teams'][$visitor])) {
                $bad($label . ': the away team is not one of the teams above.');
                continue;
            }
            if ($home === $visitor) {
                $bad($label . ' has the same team on both sides.');
                continue;
            }
            $status = $str($g, 'status', 'scheduled');
            if (!in_array($status, ['scheduled', 'ongoing', 'completed'], true)) {
                $bad($label . ': status must be scheduled, ongoing or completed.');
                continue;
            }
            $time = $str($g, 'time');
            $stamp = $time === '' ? time() : strtotime($time);
            if ($stamp === false) {
                $bad($label . ': "' . $time . '" is not a date this understands.');
                continue;
            }

            $spec['games'][$id] = [
                'id' => $id,
                'home' => $home,
                'visitor' => $visitor,
                'field' => $str($g, 'field', '1'),
                'time' => date('Y-m-d H:i:00', $stamp),
                'name' => $str($g, 'name', 'Game ' . $id),
                'status' => $status,
            ];
        }

        return ['spec' => $spec, 'problems' => $problems];
    }

    /** The description as stored, or null. */
    public static function load(?string $path = null): ?array
    {
        $path ??= self::STORE;
        if (!is_file($path)) {
            return null;
        }
        $raw = json_decode((string) @file_get_contents($path), true);

        return is_array($raw) ? $raw : null;
    }

    /** Store the description. Temp-file-and-rename, like every other store here. */
    public static function save(array $spec, ?string $path = null): bool
    {
        $path ??= self::STORE;
        $dir = dirname($path);
        if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
            return false;
        }
        $json = json_encode(
            self::forStorage($spec),
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
        if ($json === false) {
            return false;
        }
        $tmp = $path . '.' . getmypid() . '.tmp';
        if (@file_put_contents($tmp, $json . "\n", LOCK_EX) === false) {
            return false;
        }
        if (!@rename($tmp, $path)) {
            @unlink($tmp);

            return false;
        }

        return true;
    }

    /** Teams and games as lists rather than id-keyed maps, which is how a person reads them. */
    public static function forStorage(array $spec): array
    {
        $out = $spec;
        $out['teams'] = array_values($spec['teams'] ?? []);
        $out['games'] = array_values($spec['games'] ?? []);

        return $out;
    }

    /** A directory name for an event, stable across edits to everything else. */
    public static function slug(array $spec): string
    {
        $slug = strtolower(preg_replace('/[^A-Za-z0-9]+/', '-', $spec['event'] ?? '') ?? '');
        $slug = trim($slug, '-');

        return $slug === '' ? 'event' : $slug;
    }

    /**
     * Write the capture every page reads.
     *
     * @return array{ok: bool, files: list<string>, error?: string}
     */
    public static function build(array $spec, string $outDir): array
    {
        if (!is_dir($outDir) && !@mkdir($outDir, 0775, true) && !is_dir($outDir)) {
            return ['ok' => false, 'files' => [], 'error' => 'Cannot create ' . $outDir];
        }
        if (!is_writable($outDir)) {
            return ['ok' => false, 'files' => [], 'error' => $outDir . ' is not writable'];
        }

        $now = time();
        $teams = $spec['teams'];
        $games = $spec['games'];
        $pool = $spec['pool'];
        $type = $spec['type'];
        $seriesName = ucfirst($type);

        // Reservations are how a field gets a NAME; one per field in use. This
        // is what makes /s/field/1/overlay — a stage that follows a field all
        // day — resolve to anything.
        $fields = [];
        foreach ($games as $g) {
            if (!in_array($g['field'], $fields, true)) {
                $fields[] = $g['field'];
            }
        }
        $reservations = [];
        $reservationOf = [];
        foreach ($fields as $n => $field) {
            $reservationOf[$field] = 500 + $n;
            $reservations[] = [
                'id' => 500 + $n,
                'location' => 400,
                'fieldname' => $field,
                'reservationgroup' => $spec['event'],
                'name' => $spec['place'],
            ];
        }

        $seasonInfo = [
            'season_id' => $spec['season'],
            'name' => $spec['event'],
            'starttime' => date('Y-m-d H:i:s', $now),
            'endtime' => date('Y-m-d H:i:s', $now + 86400),
            'iscurrent' => 1,
            'type' => 'outdoor',
            'istournament' => 1,
            'organizer' => $spec['organizer'],
            'public_event' => 1,
            'api_public' => 1,
            'maintenance_mode' => 0,
            'event_readonly' => 0,
        ];

        $poolInfo = [
            'pool_id' => self::POOL_ID,
            'name' => $pool['name'],
            'ordering' => 1,
            'visible' => 1,
            'teams' => count($teams),
            'timeoutlen' => $pool['timeoutlen'],
            'halftime' => $pool['halftime'],
            'winningscore' => $pool['winningscore'],
            'timecap' => $pool['timecap'],
            'scorecap' => $pool['scorecap'],
            'timeouts' => $pool['timeouts'],
            'timeoutsper' => $pool['timeoutsper'],
            'drawsallowed' => 0,
            'series' => self::SERIES_ID,
            'seriesname' => $seriesName,
            'season' => $spec['season'],
        ];

        // No stats, no seed, no final_standing, no games/wins/losses: this event
        // has not been played, and Live! would send those as zeroes.
        $teamNode = static fn (array $t): array => [
            'name' => $t['name'],
            'team_id' => $t['id'],
            'abbreviation' => $t['short'],
            'series' => self::SERIES_ID,
            'seriesname' => $seriesName,
            'pool' => self::POOL_ID,
            'poolname' => $pool['name'],
            'season' => $spec['season'],
            'seasonname' => $spec['event'],
            'type' => $type,
            'valid' => 1,
            'photos' => [],
        ];

        $files = [];
        $write = static function (string $name, array $body) use ($outDir, &$files): bool {
            $json = json_encode(
                $body,
                JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
            );
            if ($json === false) {
                return false;
            }
            $tmp = $outDir . '/' . $name . '.tmp';
            if (@file_put_contents($tmp, $json . "\n") === false || !@rename($tmp, $outDir . '/' . $name)) {
                @unlink($tmp);

                return false;
            }
            $files[] = $name;

            return true;
        };

        $listed = [];
        foreach ($games as $g) {
            $row = [
                'game_id' => $g['id'],
                'hometeam' => $g['home'],
                'visitorteam' => $g['visitor'],
                'reservation' => $reservationOf[$g['field']],
                'time' => $g['time'],
                'valid' => 1,
                'halftime' => $pool['halftime'],
                'name' => (string) $g['id'],
                'pool' => self::POOL_ID,
                'gamename' => $g['name'],
                'gameschedulingname' => $g['name'],
                'pools' => (string) self::POOL_ID,
                'status' => $g['status'],
            ];
            // The score is the field that must not appear on a scheduled game:
            // a 0-0 in the list reads as a game in progress rather than as one
            // that has not begun.
            if ($g['status'] !== 'scheduled') {
                $row['hasstarted'] = 1;
            }
            $listed[] = $row;
        }
        if (!$write('games.json', ['games' => $listed])) {
            return ['ok' => false, 'files' => $files, 'error' => 'Cannot write games.json'];
        }

        foreach ($games as $g) {
            $home = $teams[$g['home']];
            $visitor = $teams[$g['visitor']];
            $ongoing = $g['status'] === 'ongoing';
            $started = $g['status'] === 'scheduled' ? 0 : 1;

            $ok = $write('games-' . $g['id'] . '.json', [
                'game_result' => [
                    'game_id' => $g['id'],
                    'time' => $g['time'],
                    'hometeam' => $home['id'],
                    'visitorteam' => $visitor['id'],
                    'hometeamname' => $home['name'],
                    'visitorteamname' => $visitor['name'],
                    'homescore' => 0,
                    'visitorscore' => 0,
                    'homevalid' => 1,
                    'visitorvalid' => 1,
                    'valid' => 1,
                    'reservation' => $reservationOf[$g['field']],
                    'halftime' => $pool['halftime'],
                    'isongoing' => $ongoing ? 1 : 0,
                    'hasstarted' => $started,
                    'islive' => $ongoing ? 1 : 0,
                    'forfeit' => 0,
                    'pool' => self::POOL_ID,
                    'gamename' => $g['name'],
                    'name' => (string) $g['id'],
                    'status' => $g['status'],
                    // The clock belongs to match control, which writes these
                    // three fields itself. Null is "nobody has started it".
                    'timer_start' => null,
                    'timer_pause_start' => null,
                    'timer_paused_duration' => 0,
                ],
                'game_info' => [
                    'game_id' => $g['id'],
                    'hometeam' => $home['id'],
                    'hometeamname' => $home['name'],
                    'hometeamshortname' => $home['short'],
                    'visitorteam' => $visitor['id'],
                    'visitorteamname' => $visitor['name'],
                    'visitorteamshortname' => $visitor['short'],
                    'pool' => self::POOL_ID,
                    'time' => $g['time'],
                    'homescore' => 0,
                    'visitorscore' => 0,
                    'timecap' => $pool['timecap'],
                    'scorecap' => $pool['scorecap'],
                    'winningscore' => $pool['winningscore'],
                    'drawsallowed' => 0,
                    'series' => self::SERIES_ID,
                    'season' => $spec['season'],
                    'seriesname' => $seriesName,
                    'poolname' => $pool['name'],
                    'isongoing' => $ongoing ? 1 : 0,
                    'hasstarted' => $started,
                    'placename' => $spec['place'],
                    'fieldname' => $g['field'],
                ],
                'seasoninfo' => $seasonInfo,
                'poolinfo' => $poolInfo,
                // Nobody has scored. An empty list is the honest answer, and
                // every derivation here — hold, break, the ABBA slot, top
                // scorer — reads it as "no points yet" rather than as missing.
                'goals' => [],
                'gameevents' => [],
                'mediaevents' => [],
                'hometeam_scoreboard' => [],
                'visitorteam_scoreboard' => [],
                'homecaptain' => null,
                'awaycaptain' => null,
                'teams' => [
                    'hometeam' => $teamNode($home),
                    'visitorteam' => $teamNode($visitor),
                ],
            ]);
            if (!$ok) {
                return ['ok' => false, 'files' => $files,
                    'error' => 'Cannot write games-' . $g['id'] . '.json'];
            }
        }

        // One file per team. `players` is empty and stays that way: a squad is
        // written to conf/ by the desk and merged over this by the provider.
        $index = [];
        foreach ($teams as $t) {
            $index[(string) $t['id']] = [
                'name' => $t['name'],
                'team_id' => $t['id'],
                'abbreviation' => $t['short'],
                'series' => self::SERIES_ID,
            ];
            $write('teams-' . $t['id'] . '.json', $teamNode($t) + [
                'club' => null,
                'clubname' => null,
                'country' => null,
                'countryname' => null,
                'flagfile' => null,
                'players' => [],
            ]);
        }
        $write('teams.json', ['teams' => $index]);

        $write('reference.json', [
            'season' => $seasonInfo,
            'series' => [[
                'series_id' => self::SERIES_ID, 'name' => $seriesName, 'ordering' => 'A',
            ]],
            'pools' => [[
                'pool_id' => self::POOL_ID,
                'poolname' => $pool['name'],
                'type' => 1,
                'series_id' => self::SERIES_ID,
                'visible' => 1,
                'ordering' => 1,
            ]],
            'pool_placements' => [],
            'teams' => array_values(array_map(
                static fn (array $t): array => [
                    'team_id' => $t['id'],
                    'name' => $t['name'],
                    'abbreviation' => $t['short'],
                    'series' => self::SERIES_ID,
                ],
                $teams
            )),
            'countries' => [],
            'reservations' => $reservations,
        ]);

        // Live!'s own settings, as this event would have them. The tournament
        // logo is the one that matters: a RECORDED capture carries Live!'s path
        // into live/conf/, which a standalone installation does not have, and
        // the stage then 404s once per load. Authored, it points at something
        // real or at nothing at all.
        $write('config.json', [
            'config' => [
                'LIVE_SEASON_ID' => $spec['season'],
                'TOURNAMENT_NAME' => $spec['event'],
                'TOURNAMENT_LOCATION' => $spec['place'],
                'TV_SCREEN_LOGO_PATH' => $spec['logo'] === '' ? null : $spec['logo'],
                'FIELD_NAMES' => $fields,
                'SHOW_TOP_STATS' => false,
                'SHOW_SPIRIT_COMMENTS' => false,
            ],
        ]);

        // When each game was "recorded". All at the same instant, because they
        // were authored at once — unlike a real capture, where two games taken
        // minutes apart must each carry their own or one clock replays out by
        // the gap.
        $write('manifest.json', [
            'games' => array_combine(
                array_map('strval', array_keys($games)),
                array_fill(0, max(count($games), 1), $now)
            ) ?: [],
            'captured_at' => $now,
            'captured_iso' => gmdate('Y-m-d\TH:i:s\Z', $now),
            'season' => $spec['season'],
            'source' => 'Overlays\\Event',
        ]);

        // A game removed from the description must lose its payload too, or the
        // Studio keeps offering a game nothing else knows about.
        $keep = array_flip($files);
        foreach ((array) @scandir($outDir) as $entry) {
            if (!is_string($entry) || !preg_match('/^(games|teams|playerevents)-\d+\.json$/', $entry)) {
                continue;
            }
            if (!isset($keep[$entry])) {
                @unlink($outDir . '/' . $entry);
            }
        }

        return ['ok' => true, 'files' => $files];
    }
}
